config/routes.rb
Rails.application.routes.draw do
  resources :flats
  resources :club_passes do
    resources :orders, only: %i[new create edit update] do
      resources :reviews
    end
  end
  devise_for :users
  root 'pages#home'
  resources :orders, only: %i[index show destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/club_pass.rb
class ClubPass < ApplicationRecord
  belongs_to :user
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :club_pass
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/club_passes_controller.rb
class ClubPassesController < ApplicationController
  def index
    @club_passes = ClubPass.all
  end

  def show
    @club_pass = ClubPass.find(params[:id])
  end

  def new
    @club_pass = ClubPass.new
  end

  def create
    @club_pass = ClubPass.new(club_pass_params)
    @club_pass.user = current_user
    if @club_pass.save
      redirect_to club_passes_path
    else
      render 'new'
    end
  end

  private

  def club_pass_params
    params.require(:club_pass).permit(:category, :description, :price, :start_date, :end_date)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]

  # GET /flats or /flats.json
  def index
    @flats = Flat.all
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat}),
        marker_html: render_to_string(partial: "marker",locals: {flat: flat})
      }
  end

  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address)
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :set_club_pass, only: %i[ new create edit update]

  # GET /orders or /orders.json
  def index
    @orders = Order.where(user: current_user)
  end

  # GET /orders/1 or /orders/1.json
  def show
    @orders = Order.find(params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new
    @order.user = current_user
    @order.club_pass = @club_pass

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def set_club_pass
      @club_pass = ClubPass.find(params[:club_pass_id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit()
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @flats = Flat.all
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat}),
        marker_html: render_to_string(partial: "marker",locals: {flat: flat})
      }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
    @reviews = Review.find(params[:id])
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:order_id, :content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/club_passes/_form.html.erb
<%= form_with(model: club_pass, local: true) do |f| %>
  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :start_date %>
  <%= f.date_field :start_date %>

  <%= f.label :end_date %>
  <%= f.date_field :end_date %>

  <%= f.submit %>
<% end %>

app/views/club_passes/index.html.erb
<h1>list of club passes</h1>
<%= link_to "add new club pass", new_club_pass_path  %>
<ul>
  <% @club_passes.each do |club_pass| %>
    <li><%= link_to club_pass.category, club_pass%></li>
  <% end %>

</ul>

app/views/club_passes/new.html.erb
<h1>New Club</h1>
<%= render "form", club_pass: @club_pass %>

app/views/club_passes/show.html.erb
<h1><%= @club_pass.category %></h1>
<%= link_to "buy this pass", new_club_pass_order_path(@club_pass) %>

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>">
  <p>
    <strong>Name:</strong>
    <%= flat.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= flat.address %>
  </p>

</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}, class: "d-none"}
%>

app/views/flats/_info_window.html.erb
<h2><%= flat.name %></h2>
<p><%= flat.address %></p>

app/views/flats/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

<div class="badge rounded-pill bg-primary fs-6">
  <%= flat.name %>
</div>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Show this flat", @flat %> |
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flats</h1>

<div id="flats">
  <% @flats.each do |flat| %>
    <%= render flat %>
    <p>
      <%= link_to "Show this flat", flat %>
    </p>
  <% end %>
</div>

<%= link_to "New flat", new_flat_path %>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flat %>

<div>
  <%= link_to "Edit this flat", edit_flat_path(@flat) %> |
  <%= link_to "Back to flats", flats_path %>

  <%= button_to "Destroy this flat", @flat, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CLUBEPass</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "custom", "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  </nav>

  </div>
    <%= yield %>
  </body>
</html>
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
      <span class="text-muted">© 2023 Clube Pass</span>
    </div>
  </footer>
</body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for [club_pass, order] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>your new pass:</strong>
    <%= order.club_pass.category %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

app/views/orders/new.html.erb
<h1>Finish Order</h1>

<%= render "form", order: @order, club_pass: @club_pass %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Congratulations! You just bought your new pass!</h1>

<%= render @order %>

<div>
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/pages/_info_window.html.erb
<h2><%= flat.name %></h2>
<p><%= flat.address %></p>

app/views/pages/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

<div class="badge rounded-pill bg-primary fs-6">
  <%= flat.name %>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="style.css">
    <title>My Colorful Landing Page</title>
</head>
<body>
    <div class="container">
        <header>
            <h1>Clube Pass</h1>
        </header>

        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Packages</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>

    <div class="container">
        <section class="main-content">
            <h2>Packages</h2>
            <p>At Clube Pass you can find the closest clube to spend your summer days with your family.
</p>
        </section>
    </div>

    <div class="container">
        <section class="services">
            <h2>Choose your pass</h2>
            <ul>
                <li>Day Pass</li>
                <li>Monthly Pass</li>
                <li>Make your own pass</li>
            </ul>
        </section>
    </div>
<h1>Welcome to CLUBE-PASS!</h1>

  <% if user_signed_in? %>
    <p>Welcome, <%= current_user.email %></p>
     <%= link_to "browse clube_pass", club_passes_path %>
    <%= link_to "browse my orders", orders_path %>
    <%= link_to "logout", destroy_user_session_path, data: {turbo_method: :delete} %>
  <% else %>
    <p>Please sign up or log in to continue.</p>
    <%= link_to "sign up", new_user_registration_path %>
    <%= link_to "login", new_user_session_path %>
  <% end %>
    <div class="container">
    <p style="color: green"><%= notice %></p>

<h1>Flats</h1>

<div id="flats">
  <% @flats.each do |flat| %>
    <%= render flat %>
    <p>
      <%= link_to "Show this flat", flat %>
    </p>
  <% end %>
</div>

<%= link_to "New flat", new_flat_path %>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>

    <div class="container">
        <section class="contact">
            <h2>Contact Us</h2>
            <p>Email: clubepass@gmail.com</p>
            <p>Phone: (000) 00000</p>
        </section>
    </div>

    <footer>
        <div class="container">
            <p>&copy; Write a review</p>
        </div>
    </footer>
</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :offer %>
    <%= f.input :text %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>User:</strong>
    <%= review.user_id %>
  </p>

  <p>
    <strong>Offer:</strong>
    <%= review.offer_id %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= review.text %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<div id="reviews">
  <% @reviews.each do |review| %>
    <%= render review %>
    <p>
      <%= link_to "Show this review", review %>
    </p>
  <% end %>
</div>

<%= link_to "New review", new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <%= link_to "Edit this review", edit_review_path(@review) %> |
  <%= link_to "Back to reviews", reviews_path %>

  <%= button_to "Destroy this review", @review, method: :delete %>
</div>